name: dbtechlab2
services:
  redis:
    image: redis:7-alpine
    container_name: dbtl2-redis
    command: >
      sh -c "redis-server --appendonly yes
             --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a $REDIS_PASSWORD -h 127.0.0.1 ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 3s
    restart: unless-stopped
    networks:
      - ml_net
    env_file:
      - .env

  model-service:
    image: ${MODEL_IMAGE}
    container_name: dbtl2-model
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - ml_net
    env_file:
      - .env

volumes:
  redis_data:

networks:
  ml_net:
    driver: bridge

